// src/infrastructure/audit/AuditEvents.ts
// Audit event type definitions

export const AUDIT_EVENTS = {
  // System
  SYSTEM_STARTED: 'SYSTEM_STARTED',
  SYSTEM_STOPPED: 'SYSTEM_STOPPED',
  CONFIG_CHANGED: 'CONFIG_CHANGED',
  
  // Data
  DATA_COLLECTOR_STARTED: 'DATA_COLLECTOR_STARTED',
  DATA_COLLECTOR_STOPPED: 'DATA_COLLECTOR_STOPPED',
  DATA_COLLECTION_ERROR: 'DATA_COLLECTION_ERROR',
  
  // Gates
  GATE_EVALUATION: 'GATE_EVALUATION',
  PERMISSION_CHANGE: 'PERMISSION_CHANGE',
  
  // Trader
  COMMAND_RECEIVED: 'COMMAND_RECEIVED',
  ORDER_PREPARED: 'ORDER_PREPARED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
  
  // Override
  OVERRIDE_REQUESTED: 'OVERRIDE_REQUESTED',
  OVERRIDE_GRANTED: 'OVERRIDE_GRANTED',
  OVERRIDE_DENIED: 'OVERRIDE_DENIED',
  
  // Execution
  EXECUTION_ATTEMPT: 'EXECUTION_ATTEMPT',
  EXECUTION_SUCCESS: 'EXECUTION_SUCCESS',
  EXECUTION_FAILURE: 'EXECUTION_FAILURE',
  EXECUTION_BLOCKED: 'EXECUTION_BLOCKED',
  
  // Auto-Protect
  AUTO_PROTECT_ENABLED: 'AUTO_PROTECT_ENABLED',
  AUTO_PROTECT_DISABLED: 'AUTO_PROTECT_DISABLED',
  AUTO_PROTECT_TRIGGERED: 'AUTO_PROTECT_TRIGGERED',
  AUTO_PROTECT_EXECUTED: 'AUTO_PROTECT_EXECUTED',
  AUTO_PROTECT_FAILED: 'AUTO_PROTECT_FAILED',
  
  // Security
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  KILLSWITCH_ACTIVATED: 'KILLSWITCH_ACTIVATED',
  KILLSWITCH_DEACTIVATED: 'KILLSWITCH_DEACTIVATED',
  
  // Violations
  TIER1_VIOLATION: 'TIER1_VIOLATION',
} as const;

export type AuditEventType = typeof AUDIT_EVENTS[keyof typeof AUDIT_EVENTS];

export class AuditEvents {
  static isValidEvent(event: string): event is AuditEventType {
    return Object.values(AUDIT_EVENTS).includes(event as AuditEventType);
  }
}
